### ISSUE TITLE
Add code to keep images sized within brower window

### ISSUE THREAD

**Issue by geealbers** [thegetty/cultural-heritage-mass-atrocities#30]
Like in [_Living Matter_](https://github.com/thegetty/living-matter/commit/35991d1d74e2cd683a62e2f403a182ef13ecedaa):

```css
/* Ensure that images can always be seen in full within the user's window withouth scrolling */
@media screen {
  .content figure .quire-figure__image {
    max-height: calc(100vh - 6rem);
    width: auto;
  }
}
```
