### ISSUE TITLE
Resolve use of "Image:" preceding credit lines for figures

### ISSUE THREAD

**Issue by geealbers** [thegetty/cultural-heritage-mass-atrocities#68]
As requested, I've globally added "Image:" to precede the credit lines for figures. There are however, by my count, eight instances where some further editorial tweaking is probably called for. Namely those instances that now read "Image: Photo...". I've copied them below for references.

```yaml
    label: "Figure 5.11"
    caption: "Bayt al-ḥikma, Baghdad, view of the burned second floor"
    credit: "Image: Photograph courtesy of Nabil al-Tikriti"

    label: "Figure 7.2"
    caption: "Pilgrims at the shrine of Imam Aptah."
    credit: "Image: Photo courtesy of Rahile Dawut"

    label: "Figure 7.4"
    caption: "Friday prayer at a local mosque in southern Xinjiang in 2012."
    credit: "Image: Photo courtesy of Aziz Isa"

    label: "Figure 7.5"
    caption: "A local graveyard in southern Xinjiang in 2012."
    credit: "Image: Photograph by the author"

    label: "Figure 13.6"
    caption: "Inside the Dār al-Makhṭūṭāt, 2009"
    credit: "Image: Photograph by the author"

    label: "Figure 13.6"
    caption: "Inside the Dār al-Makhṭūṭāt, 2009"
    credit: "Image: Photograph by the author"

    label: "Figure 13.8"
    caption: "Stack of manuscripts in a private library in Yemen, 2019"
    credit: "Image: Photograph by the Imam Zayd b. Ali Cultural Foundation, Sana’a, reproduced with kind permission"

    label: "Figure 31.4"
    caption: "Ras Almargeb, Libya, where forces loyal to the government of Muammar Gaddafi stationed six vehicles of a mobile radar/communications unit in the hope they would not be targeted because of the proximity to the Roman fort. All six were destroyed by precision weapons leaving the Roman building intact."
    credit: "Image: Photo © Karl Habsburg"


```
